
import { ReactNode } from 'react';
import { AppBar, Toolbar, Typography, Container, Button, Box, ThemeProvider, CssBaseline } from '@mui/material';
import Link from 'next/link';
import { Metadata } from 'next';
import { Inter } from 'next/font/google'
import theme from '../theme';
import Image from 'next/image';
import HeaderBar from '@/components/shared/headerbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Usentric",
  description: "Generated by create next app",
  icons: { icon: "/usentric.svg" }
};

export default function Layout({ children }: { children: ReactNode }) {
  
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body style={{ margin: '0' }} className={inter.className}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <Box sx={{ backgroundColor: 'background.default', color: 'text.primary', minHeight: '100vh' }}>
            {children}
          </Box>
        </ThemeProvider>
      </body>
    </html>
  );
}